### PR TITLE
Modernized many argument checks to use nameof() instead of string literals

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by DamianSuess** [comment]
Nice PR. Wow, you really went through this with a fine-tooth comb!

I'm with you in regards to the use of `nameof(..)` 👍

**Comment by Lehonti** [comment]
> Nice PR. Wow, you really went through this with a fine-tooth comb!
> 
> I'm with you in regards to the use of `nameof(..)` 👍

Yeah, and easy changes like this can be made wholesale :)

**Comment by Lehonti** [comment]
Any plans to review and merge this? @gluckez @hwthomas

**Comment by gluckez** [comment]
@Lehonti great work! looks good to me. I'll run the pipe first but it should be fine

**Pull request merged**
