### PR TITLE
Deleted Git related projects from solution.

### PR DESCRIPTION
**Pull request by lextm**
Tested on an Ubuntu 20.04 machine, and the problematic projects must be removed from the solution for the code base to compile without errors.

The following packages are required, but not documented in README-oe-modifications.txt,

* mono-complete (need further instructions from mono-project.com)
* fsharp
* gtk-sharp2
* dotnet-sdk-5.0 (need further instructions from dot.net)
* autoconf
* automake
* intltool

### CODE REVIEW

**Comment by lytico** [comment]
on my machine, git-related projects compile without problems (https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.2.6). what errors you get?

**Comment by lytico** [comment]
& dotnet-sdk-5.0 : i've dotnet-sdk-3.1, working too.

**Comment by lextm** [comment]
LibGit2Sharp failed to compile with a famous error of its own. I will try to use a Travis CI clean VM then since your machine works.

**Comment by hwthomas** [comment]
Have you managed to track down the LibGit2Sharp error yet?   I still get this on clean VMs (both ubuntu and Arch) and can't seem to get to the bottom of it. Any help would be appreciated.

**Comment by lytico** [comment]
what error you get exactly?

**Comment by lextm** [comment]
I tried several VMs, and always got
```
"/home/lextm/dotdevelop/main/Main.sln" (default target) (1) ->
"/home/lextm/dotdevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj" (default target) (59) ->
"/home/lextm/dotdevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj" (default target) (60:2) ->
(CoreCompile target) -> 
  VSEditor/TextEditorFactoryService.cs(42,18): error CS0122: 'GuardedOperations' is inaccessible due to its protection level [/home/lextm/dotdevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj]


"/home/lextm/dotdevelop/main/Main.sln" (default target) (1) ->
"/home/lextm/dotdevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj" (default target) (142) ->
"/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj" (default target) (143:2) ->
(GetBuildVersion target) -> 
  /home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: lib/linux-x64/libgit2-106a5f2.so assembly:<unknown assembly> type:<unknown type> member:(null) [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary () [0x00002] in <c6ddab362adb4977b9e6460e3b7d98f1>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at LibGit2Sharp.Core.NativeMethods..cctor () [0x00045] in <c6ddab362adb4977b9e6460e3b7d98f1>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:    --- End of inner exception stack trace --- [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path (LibGit2Sharp.ConfigurationLevel level, System.String path) [0x00000] in <c6ddab362adb4977b9e6460e3b7d98f1>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths (LibGit2Sharp.ConfigurationLevel level, System.String[] paths) [0x0001a] in <c6ddab362adb4977b9e6460e3b7d98f1>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo (System.String pathUnderGitRepo, System.Boolean useDefaultConfigSearchPaths) [0x00025] in <897015f416174969b83606561766ed67>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at Nerdbank.GitVersioning.VersionOracle.Create (System.String projectDirectory, System.String gitRepoDirectory, Nerdbank.GitVersioning.ICloudBuild cloudBuild, System.Nullable`1[T] overrideBuildNumberOffset, System.String projectPathRelativeToGitRepoRoot) [0x00017] in <897015f416174969b83606561766ed67>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner () [0x000c5] in <be4381b7946142508d2f747b9460e2ef>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at MSBuildExtensionTask.ContextAwareTask.Execute () [0x0005e] in <be4381b7946142508d2f747b9460e2ef>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <17ac7020b8724cc3ab2118010c2e573d>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]
/home/lextm/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <17ac7020b8724cc3ab2118010c2e573d>:0  [/home/lextm/dotdevelop/main/external/libgit2sharp/LibGit2Sharp/LibGit2Sharp.csproj]

    584 Warning(s)
    2 Error(s)

```

**Comment by lytico** [comment]
i'm just trying on a plain ubuntu 20.04, same error as you. 
strange ... why on my machine it works?

**Comment by hwthomas** [comment]
Yes, that's exactly what I'm getting - and it's the same on a plain fedora VM as well.  However, like you, on my main (Arch) PC, it compiles with no errors!  I've tried building LibGit2Sharp with msbuild -v:d LibGit2Sharp.csproj but I'm no nearer finding the difference.  The file that can't be found (lib/linux-x64/libgit2-106a5f2.so) is correct in the libgit2sharp.dll.config file, and is in the right place, so I don't understand why it can't be found.

**Comment by hwthomas** [comment]
On dotdevelop-8.2.6 I get just the 1 error (the Nerdbank.GitVersioning one listed for 8.4.3), but not the other one.  I wonder what @lextm meant by "a famous error of its own"?

**Comment by knocte** [comment]
Hey guys, keep up the good work! But if you want more clarity on what can still build or not, maybe we have to setup a quick GithubCI lane? I did one recently for macOS (check this: https://github.com/mono/monodevelop/issues/9174 ) and shouldn't be hard to make it run on Ubuntu 20.04 LTS.

**Comment by lextm** [comment]
@knocte Yeah, setting up a CI pipeline should be a good way to guarantee that everyone is on the same page (instead of relying too much on individual machines). But the tricky part right now is LibGit2Sharp fails to compile on clean Ubuntu 20.04 machines (I tried 3, and others tried several as well).

So I think the core question here is whether to investigate and resolve the LibGit2Sharp compilation issue first. To me, it is more important to have a working CI pipeline with succeeded builds, so I rather remove all Git projects from the solution and have the main code base built and shared among contributors (**the goal of this pull request**).

Users requiring Git can always use another Git client, and contributors can later revisit LibGit2Sharp and see how to resolve it (but it has been a famous issue so I don't expect it is easy to fix).

**Comment by knocte** [comment]
> So I think the core question here is whether to investigate and resolve the LibGit2Sharp compilation issue first.

Well, it seems that the CI goal wouldn't be possible without this PR anyway, so maybe it should be included in this PR. I mean, to make your point crystal clear you could add the GithubActions CI lane as a first commit in this PR (and as you say, its status would be red, as in failing), and then your second commit would fix it (and it would be marked with a green icon).

**Comment by lytico** [comment]
I started an issue about CI:
see: https://github.com/dotdevelop/dotdevelop/issues/29

**Comment by lytico** [comment]
I started an issue about MonoDevelop.VersionControl.Git:
https://github.com/dotdevelop/dotdevelop/issues/30

**Comment by lytico** [comment]
done in https://github.com/dotdevelop/dotdevelop/tree/dotdevelop_oe_8.4.3.12_NoGit

**Pull request closed without merging**
