### PR TITLE
Install full software environment explicitly into the CI rather than rely …

### PR DESCRIPTION
**Pull request by hwthomas**
…on the pre-installed github software.  

This fixes Issue #64, and will allow PR #63 to pass all checks

### CODE REVIEW

**Comment by lextm** [comment]
You might find #45 kind of familiar.

**Comment by hwthomas** [comment]
Can't explain what is going on here.  Will investigate further. Apologies for the noise.  
@lextm - yes, I found your testing in #45 useful.

**Comment by hwthomas** [comment]
I've done some more testing, but failed to get the CI workflow to run without error.  The current ``main`` one has 4 errors, all apparently from changes in the fsharp versions in the github ubuntu 20.04 environment.  Installing software explicitly, which seemed to work initially, now fails with over 100 errors, some such as  
 ``DOWNLOADNUPKG : Ssl error : 1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`` which I have no idea how to tackle!  
@lextm: I've copied your amended workflow from #45 to try out using a container, which would hopefully start from a more basic ubuntu repo, but even this now fails to run.  
Using VMs, ubuntu 20.04, ubuntu 21.04, and fedora 33 all build and run with no problems, following the Wiki instructions, so it appears to be the github CI workflow environment which is at the root of the problem.

**Comment by lextm** [comment]
The cause is rather simple that Microsoft is retiring NuGet.org v2 API, https://docs.microsoft.com/en-us/nuget/nuget-org/overview-nuget-org#api-endpoint-for-nugetorg

If you override NuGet settings to use v3, I think it should work again.

**Comment by hwthomas** [comment]
I've updated the CI workflow file to use the docker image "ubuntu:20.04" and explicitly installed all the necessary packages into that. After some trial-and-error testing in my ``CI_tests`` branch, I have a working version that passes the CI runs.  However, after  transferring this version to the ``fix_CI_env`` branch, the same code fails, with multiple errors of the form ``DOWNLOADNUPKG : Ssl error : 1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`` as seen in the runs above.  I'm not sure what to make of this: usually intermittent failures suggest concurrency issues, but perhaps there's another possibility?  
@lextm: following your suggestion, I checked the dotdevelop/.NuGet.config file, but it appears to be using v3 already.  Is there somewhere else to look?

**Comment by hwthomas** [comment]
From the logs, NUnitRunner.csproj (main/src/addins/MonoDevelop.UnitTesting...), TestRunner.csproj (main/tests/TestRunner...), and UserInterfaceTests.csproj (main/tests/UserInterfaceTests...) all have specific references to NUnitV2 (and rather hacky ones too, as explained in the comments).  Whether this is all, I don't yet know.

**Comment by lytico** [comment]
@hwthomas ready to merge, what do you say?

**Comment by hwthomas** [comment]
@lytico - I've had several consistent runs now in my `fix_CI_env` and `CI_tests` branches, so I'm happy if you are.  

The `Ssl error : 1000007d` problems seemed to be caused by trying to access `nuget.org/v2` sites, but I've not been able to track down where these calls originate in the build, and I still don't understand how or why the failures were intermittent.  
I've squashed all the 'trial-and-error' commits into a single one to make life a bit simpler

**Comment by lytico** [comment]
> how or why the failures were intermittent.

i have this on other CI's as well, seems to be a workload problem on github or nuget.org, maybe ...

**Comment by lytico** [comment]
>  I checked the dotdevelop/.NuGet.config file, but it appears to be using v3 already

but maybe on the tons of subprojects they are not?

**Comment by hwthomas** [comment]
>i have this on other CI's as well, seems to be a workload problem on github or nuget.org, maybe ...  

That's interesting.  I was assuming it was a concurrency issue, but couldn't find a way to run the CI in a single thread to check.  At least I'm not the only one to have had a problem!

**Comment by hwthomas** [comment]
>but maybe on the tons of subprojects they are not?  

A full search of the repo shows that `nuget.org/api/v2` **only** occurs in the `external/fsharpbinding` project, in files `paket.dependencies` and `.nuget/NuGet.targets`  
Successful run CI#80 (https://github.com/dotdevelop/dotdevelop/runs/3232143181?check_suite_focus=true#step:6:4311) shows all the fsharpbinding dependencies being restored without problem, and without needing to download from `https://www.nuget.org/api/v2/`.  
In contrast, failing run CI#78 (https://github.com/dotdevelop/dotdevelop/runs/3161054112?check_suite_focus=true#step:4:4324) tries to access these sources and fails.  

@lytico  As this is a specific `fsharpbinding` problem, would it be better to deal with it in a separate Issue/PR?  

For this PR though, basing the CI workflow on a minimal docker image still seems worthwhile, as it gives finer control over the software environment, particularly if/when `mono` and `msbuild` versions change as .NET5 stabilises and progresses.  It also links the CI to the 'Setting up a Build Environment' Wiki pages more clearly.

**Comment by lytico** [comment]
> A full search of the repo shows that nuget.org/api/v2 only occurs in the external/fsharpbinding project, in files paket.dependencies and .nuget/NuGet.targets

what if changing to nuget.org/api/v3 in this files?
should be another PR

**Comment by hwthomas** [comment]
>what if changing to nuget.org/api/v3 in this files?

Using "https://api.nuget.org/v3/index.json" as the url in the paket.dependencies file gave an error:-   

``  Starting full restore process``.
``  Performance:``
``   - Runtime: 597 milliseconds``
``  Paket failed with``
``  -> The NuGet source https://www.nuget.org/api/v2 for package FSharp.Compiler.Service was not found in the     paket.dependencies file with sources [NuGetV3 {Url = "https://api.nuget.org/v3/index.json"; ...}``  

Where could the reference  ``https://www.nuget.org/api/v2`` for package FSharp.Compiler.Service be coming from?  As far as I can see it does not occur anywhere in the repo, so how to get rid of it?  

Any suggestions or pointers for further investigation/understanding would be much appreciated. Until then I'll leave the PR.

**Pull request merged**
