### PR TITLE
Fsharp api v3

### PR DESCRIPTION
**Pull request by hwthomas**

### CODE REVIEW

**Comment by hwthomas** [comment]
Try to fix intermittent CI failures by removing last nuget/api/v2 URLs in fsharpbinding repo.

**Comment by hwthomas** [comment]
@lytico, @knuxbbs - I'd be grateful if you could review this series of PRs (#77, #87, #90, #91) with a view to merging - perhaps into a new `develop` branch if you feel they are not yet stable enough for `main`.  

Taken together, these changes allow net5.0/net6.0 projects to be created, built and run, and would allow some more extensive testing of DotDevelop to be started - hopefully by some new contributors as well!

**Comment by gluckez** [comment]
@hwthomas @lytico I think having a develop branch is a good idea, as well as using feature branches for developers working on seperate features before they go in testing. There is already a develop branch, but the policies need to be updated to set this as the main working branch. Could you do that? it is already up to date with main.

**Comment by hwthomas** [comment]
@gluckez The `develop` branch was created by me (accidentally - I intended to be on my own fork!) but I'm not sure of the relative benefits (or problems) of having this as the default working branch.  @lytico What are your thoughts?

**Comment by gluckez** [comment]
@hwthomas there are several benefits. You could set up the policies for only allowing to merge branches into develop, so we're sure that the main release branch remains untouched until everything is tested properly. You could set up a CICD pipeline for a pre-release for others to test before making a new release. You can use wildcards to use the latest nuget packages of the dependencies on develop, before fixing them on the main branch, and the pre-release or nightly pipelines would identify issues with updated api's. this way we know we're always using the latest compatible versions. but I'll leave all that to the maintainers xD

**Pull request merged**
