### PR TITLE
use funcloader for cairo library in cairo extensions

### PR DESCRIPTION
**Pull request by gluckez**
This pr introduces a cairo library definition to centralize logic to load functions from cairo libraries for different platforms, and uses them in the cairo extensions.

### CODE REVIEW

**Comment by gluckez** [comment]
@lytico @hwthomas Can you have a look and provide some feedback on this please? I also noticed that the pipeline fails now, where it didn't before, and it builds fine locally.

**Comment by hwthomas** [comment]
@gluckez  I haven't been able to look at your code changes yet, but the CI pipeline failure is very familiar - it fails with  

`DOWNLOADNUPKG : Ssl error : 1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED `   

and very often will run OK next time.  However, you'd need to set up your own CI pipeline to be able to do that

**Comment by gluckez** [comment]
@hwthomas Thanks :) I'll have a look at that pipeline setup, maybe I can just replicate that.

**Comment by lytico** [comment]
CI related stuff should be an extra PR. it's not a good idea to mix different tasks in one PR.

**Comment by gluckez** [comment]
@lytico I added the CI related stuff on another branch on my own fork, it was just for testing anyway.

**Comment by gluckez** [comment]
@lytico and @hwthomas is it possible to review this pr? it's been open for quite a while now and doesn't break anything.

**Pull request merged**
