### PR TITLE
Windows dotdevelop xwt: Do not merge

### PR DESCRIPTION
**Pull request by MakiWolf**
Change xwt back to dotdevelop fork from https://github.com/dotdevelop/dotdevelop/pull/152.

To try open Main.sln with Visual Studio 2022 and select Monodevelop.Startup and debugwin32

Also deleted all gtk3 nuget packages because when building gtk2 it causes problems.

I have also installed gettext from https://mlocati.github.io/articles/gettext-iconv-windows.html

Small update with commenting out in main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs some lines it displays now the main ide window. But opening a file and source editor don't work on windows.

Seems that the .dll files for the addins are not build on windows

### CODE REVIEW

**Comment by MakiWolf** [comment]
I have now tried to solve the build errors with winbuild-debug.bat to also build the addins. But at least it does not start with addins.

`````
INFO [2024-02-16 18:51:17Z]: Starting MonoDevelop 8.6 Preview (8.6 build 1071)
INFO [2024-02-16 18:51:17Z]: Build Information
bdc6c3fcaf5fcac3ff467017e0c30ba68039edc5

INFO [2024-02-16 18:51:17Z]: Running on Microsoft .NET 4.0.30319.42000
INFO [2024-02-16 18:51:17Z]: Operating System: Windows 10.0.22631.0 (64-bit)
INFO [2024-02-16 18:51:17Z]: Found GTK# version 2.12.45
INFO [2024-02-16 18:51:17Z]: Using GTK+ 2.24.26
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\MonoDevelop.DotNetCore.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\Templates\Microsoft.DotNet.Common.ProjectTemplates.1.x.1.0.0-beta2-20170629-269.nupkg' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\MonoDevelop.DotNetCore.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\Templates\Microsoft.DotNet.Common.ProjectTemplates.2.0.1.0.0-beta2-20170727-301.nupkg' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\MonoDevelop.DotNetCore.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\Templates\Microsoft.DotNet.Test.ProjectTemplates.1.x.1.0.0-beta2-20170629-269.nupkg' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\MonoDevelop.DotNetCore.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.Debugger.DotNetCore\Templates\Microsoft.DotNet.Test.ProjectTemplates.2.0.1.0.0-beta2-20170727-301.nupkg' referenced in the manifest could not be found.
WARNING: [MonoDevelop.DesignerSupport,8.6] Could not load some add-in assemblies: Die Datei "C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.DesignerSupport\Xamarin.PropertyEditing.Mac.dll" konnte nicht gefunden werden.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.DesignerSupport\MonoDevelop.DesignerSupport.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\MonoDevelop.DesignerSupport\Xamarin.PropertyEditing.Mac.dll' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\MonoDevelop.VersionControl.Git.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\git2-e8b8948.dll' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\SubversionAddinWindows.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\SharpPlink-Win32.svnExe' referenced in the manifest could not be found.
ERROR: C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\SubversionAddinWindows.dll: The file 'C:\msys64\home\Marku\windowsxwt\main\build\AddIns\VersionControl\SharpSvn-DB44-20-win32.svnDll' referenced in the manifest could not be found.
WARNING: The add-in 'MonoDevelop.TextEditor,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.SourceEditor2,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Refactoring,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.PackageManagement,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Deployment,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Autotools,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Xml,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.AspNet,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Packaging,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.TextEditor.Wpf,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.GtkCore,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.DotNetCore,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
WARNING: The add-in 'MonoDevelop.Gettext,8.6' could not be updated because some of its dependencies are missing or not compatible:
  missing: MonoDevelop.DesignerSupport,8.6
INFO [2024-02-16 18:51:30Z]: Add-in loaded: MonoDevelop.Core
INFO [2024-02-16 18:51:30Z]: Add-in loaded: MonoDevelop.Ide
INFO [2024-02-16 18:51:31Z]: Add-in loaded: MonoDevelop.WindowsPlatform
INFO [2024-02-16 18:51:31Z]: Initializing Runtime MS.NET
INFO [2024-02-16 18:51:31Z]: [1 (+1)] Finding custom frameworks
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: path1
   bei System.IO.Path.Combine(String path1, String path2)
   bei MonoDevelop.Core.Runtime.LoadMSBuildLibraries() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Core\MonoDevelop.Core\Runtime.cs:Zeile 507.
   bei MonoDevelop.Core.Runtime.Initialize(Boolean updateAddinRegistry) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Core\MonoDevelop.Core\Runtime.cs:Zeile 147.
INFO [2024-02-16 18:51:31Z]: GTK: Using Gtk theme from C:\Users\Marku\AppData\Roaming\MonoDevelop\8.0\Config\share\themes\Light
INFO [2024-02-16 18:51:31Z]: [17 (+16)] Creating frameworks
INFO [2024-02-16 18:51:31Z]: Creating service: MonoDevelop.Components.Commands.CommandManager
INFO [2024-02-16 18:51:31Z]: [41 (+24)] Initializing frameworks
INFO [2024-02-16 18:51:31Z]: Service MonoDevelop.Components.Commands.CommandManager initialized in 121 ms.
FATAL ERROR [2024-02-16 18:51:31Z]: MonoDevelop failed to start. Some of the assemblies required to run MonoDevelop (for example gtk-sharp)may not be properly installed in the GAC.
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> Mono.Addins.MissingDependencyException: The required addin 'MonoDevelop.DesignerSupport,8.6' is not installed.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 732.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.LoadAddin(AddinEngineTransaction transaction, IProgressStatus statusMonitor, String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 652.
   bei Mono.Addins.AddinEngine.GetOrLoadAddin(String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 555.
   bei Mono.Addins.ExtensionNode.get_Addin() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 160.
   bei MonoDevelop.Components.Commands.ExtensionNodes.CommandCodon.CreateInstance() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands.ExtensionNodes\CommandCodon.cs:Zeile 146.
   bei Mono.Addins.InstanceExtensionNode.GetInstance() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\InstanceExtensionNode.cs:Zeile 76.
   bei Mono.Addins.ExtensionNodeEventArgs.get_ExtensionObject() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 1332.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 149.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 152.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei Mono.Addins.ExtensionContext.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 739.
   bei Mono.Addins.AddinManager.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinManager.cs:Zeile 734.
   bei MonoDevelop.Components.Commands.CommandManager.LoadCommands(String addinPath) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 134.
   bei MonoDevelop.Components.Commands.IdeCommandManager.<OnInitialize>d__1.MoveNext() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\IdeCommandManager.cs:Zeile 55.
   --- Ende der internen Ausnahmestapel▒berwachung ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei MonoDevelop.Core.BasicServiceProvider.<GetService>d__5`1.MoveNext() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Core\MonoDevelop.Core\BasicServiceProvider.cs:Zeile 82.
   --- Ende der internen Ausnahmestapel▒berwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bei System.Threading.Tasks.Task`1.get_Result()
   bei MonoDevelop.Ide.IdeStartup.Run(MonoDevelopOptions options) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide\IdeStartup.cs:Zeile 241.
   bei MonoDevelop.Ide.IdeStartup.Main(String[] args, IdeCustomizer customizer) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide\IdeStartup.cs:Zeile 755.
---> (Interne Ausnahme #0) System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> Mono.Addins.MissingDependencyException: The required addin 'MonoDevelop.DesignerSupport,8.6' is not installed.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 732.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.LoadAddin(AddinEngineTransaction transaction, IProgressStatus statusMonitor, String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 652.
   bei Mono.Addins.AddinEngine.GetOrLoadAddin(String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 555.
   bei Mono.Addins.ExtensionNode.get_Addin() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 160.
   bei MonoDevelop.Components.Commands.ExtensionNodes.CommandCodon.CreateInstance() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands.ExtensionNodes\CommandCodon.cs:Zeile 146.
   bei Mono.Addins.InstanceExtensionNode.GetInstance() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\InstanceExtensionNode.cs:Zeile 76.
   bei Mono.Addins.ExtensionNodeEventArgs.get_ExtensionObject() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 1332.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 149.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 152.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei Mono.Addins.ExtensionContext.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 739.
   bei Mono.Addins.AddinManager.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinManager.cs:Zeile 734.
   bei MonoDevelop.Components.Commands.CommandManager.LoadCommands(String addinPath) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 134.
   bei MonoDevelop.Components.Commands.IdeCommandManager.<OnInitialize>d__1.MoveNext() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\IdeCommandManager.cs:Zeile 55.
   --- Ende der internen Ausnahmestapel▒berwachung ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei MonoDevelop.Core.BasicServiceProvider.<GetService>d__5`1.MoveNext() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Core\MonoDevelop.Core\BasicServiceProvider.cs:Zeile 82.
---> (Interne Ausnahme #0) Mono.Addins.MissingDependencyException: The required addin 'MonoDevelop.DesignerSupport,8.6' is not installed.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 732.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.ResolveLoadDependencies(AddinEngineTransaction transaction, List`1 addins, Stack depCheck, String id, Boolean optional) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 753.
   bei Mono.Addins.AddinEngine.LoadAddin(AddinEngineTransaction transaction, IProgressStatus statusMonitor, String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 652.
   bei Mono.Addins.AddinEngine.GetOrLoadAddin(String id, Boolean throwExceptions) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinEngine.cs:Zeile 555.
   bei Mono.Addins.ExtensionNode.get_Addin() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 160.
   bei MonoDevelop.Components.Commands.ExtensionNodes.CommandCodon.CreateInstance() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands.ExtensionNodes\CommandCodon.cs:Zeile 146.
   bei Mono.Addins.InstanceExtensionNode.GetInstance() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\InstanceExtensionNode.cs:Zeile 76.
   bei Mono.Addins.ExtensionNodeEventArgs.get_ExtensionObject() in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 1332.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 149.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei MonoDevelop.Components.Commands.CommandManager.OnExtensionChange(Object s, ExtensionNodeEventArgs args) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 152.
   bei Mono.Addins.ExtensionNode.add_ExtensionNodeChanged(ExtensionNodeEventHandler value) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionNode.cs:Zeile 228.
   bei Mono.Addins.ExtensionContext.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\ExtensionContext.cs:Zeile 739.
   bei Mono.Addins.AddinManager.AddExtensionNodeHandler(String path, ExtensionNodeEventHandler handler) in C:\msys64\home\Marku\windowsxwt\main\external\mono-addins\Mono.Addins\Mono.Addins\AddinManager.cs:Zeile 734.
   bei MonoDevelop.Components.Commands.CommandManager.LoadCommands(String addinPath) in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:Zeile 134.
   bei MonoDevelop.Components.Commands.IdeCommandManager.<OnInitialize>d__1.MoveNext() in C:\msys64\home\Marku\windowsxwt\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\IdeCommandManager.cs:Zeile 55.<---
<---

**Comment by MakiWolf** [comment]
fixed startup now. To compile simple run winbuild-debug.bat in main directory. A lot of addins are now build but the source editor don't work actual.

**Comment by MakiWolf** [comment]
Also an interesting question is if we can use the GTK UI of the Editor also on Windows and give give up the WPF UI to have a single cross plattform code base for the Editor. Also where in the code it is defined to open up the WPF version?

Currently I have commented out some WPF parts because IWpfTextView, ... references are not found in the source code of the source code from the vseditor api.

**Comment by Bod9001** [comment]
I get 
` main\msbuild\ReferencesVSEditor.Gtk.props(52,3): error MSB4019: main\external\vs-editor-api\build\Environment.props" was not found. Confirm that the expression in the Import declaration  main\external\vs-editor-api\build\Environment.props" is correct, and that the file exists on disk. [\main\src\core\MonoDevelop.Core\MonoDevelop.Core.csproj]`
there's a bunch of very similar errors being printed as well,
when running the bat, Though could be funky stuff going on

**Comment by lextm** [comment]
It would be interesting to actually check how many Windows users are out there. VS/VS Code and even SharpDevelop are better alternatives.

Xamarin might need a Windows build of Xamarin Studio to prove that it was self sustainable even without VS, but currently does dotdevelop have the luxury to do the same?

I think Linux/GTK 3 should be the top priority, which you are the main contributor in #150, right?

**Comment by knocte** [comment]
> I think Linux/GTK 3 should be the top priority

Seconded, there's no point to cater the Windows crowd here, as they are happy with their VS/Rider/VSCode.

**Comment by MakiWolf** [comment]
> Seconded, there's no point to cater the Windows crowd here, as they are happy with their VS/Rider/VSCode.

I would say that an completly OpenSource IDE on windows will be great. VSCode is only a Text Editor and not an real open source replacement for VS. Rider is also not OpenSource.

> I think Linux/GTK 3 should be the top priority, which you are the main contributor in #150, right?

Sure the focus is to port it to gtk3 on Linux.

But I would say that if it is possible that dotdevelop will be an complety cross platform gtk3 IDE in future and gave up windows specific UI and replace it with gtk UI. This will be a long way I know.



> I get
> ` main\msbuild\ReferencesVSEditor.Gtk.props(52,3): error MSB4019: main\external\vs-editor-api\build\Environment.props" was not found. Confirm that the expression in the Import declaration main\external\vs-editor-api\build\Environment.props" is correct, and that the file exists on disk. [\main\src\core\MonoDevelop.Core\MonoDevelop.Core.csproj]`
> there's a bunch of very similar errors being printed as well,
> when running the bat, Though could be funky stuff going on

@Bod9001 is this build now starting and compiling on your system?

you also need to run git submodule init and git submodule update before running the script.

Build requieremts on windows are also:
https://mlocati.github.io/articles/gettext-iconv-windows.html
https://git-scm.com/downloads
and mono libraries which can only be downloaded from web archive (not really sure if it is building without it)
[Web Archive - MonoLibraries.msi](https://web.archive.org/web/20161003141250/https://files.xamarin.com/~jeremie/MonoLibraries.msi)
https://www.mono-project.com/download/stable/#download-win (32 bit)
and also GTK# for .NET from mono download page

**Comment by Bod9001** [comment]
yeah, was able to build with these pointers, might be worth putting them in the main MD, do note github desktop has a fit when trying to change branches so you have to do git checkout in the terminal, built okay , do note it leaves msbuild processes running in the background you have to close them manually if you do multiple builds.

of course like you said in the PR, UI elements don't work

but it looks promising
might be worth saying which version of  gettext  you need , static , shared, 32bit, 64bit?

**Comment by MakiWolf** [comment]
> might be worth saying which version of gettext you need , static , shared, 32bit, 64bit?

Currently I have installed gettext0.21-iconv1.16-shared-64 but I have not tested if the 32bit version also works.

**Comment by knocte** [comment]
> But I would say that if it is possible that dotdevelop will be an complety cross platform gtk3 IDE in future and gave up windows specific UI and replace it with gtk UI. 

I was maintainer of banshee media player in the past. The team tried hard to make it Windows compatible (basically running Gtk on Windows). Most of the time it didn't work (because almost zero upstream Gtk developers care about this OS), and a lot of hacks & workarounds had to be made. Not to mention that there was no proper way to consume the toolkit in this platform, and the team had to generate binaries (of the gtk libs and the program) ourselves.

If you truly want to make dotdevelop crossplatform, use xwt (which is being used already by dotdevelop/monodevelop in fact).

**Comment by lytico** [comment]
> I think Linux/GTK 3 should be the top priority, which you are the main contributor in https://github.com/dotdevelop/dotdevelop/pull/150, right?

i agree. there should be the priority on porting to GKT3/GtkSharp, and then, if it works, second, if the whole building process works (which is currently in a desperate state), start caring about other platforms.

**Comment by MakiWolf** [comment]
The main goal is that we have a Linux replacement for Visual Studio on Linux, but I found it also important to play with it to get windows build.

Also an interesting experiment is that you can build DebugGnome on Windows with a working text editor.

https://github.com/MakiWolf/dotdevelop/tree/windowslinuxbuild

It complains with message when starting on windows. you can simple press ok.

grafik

And also windows specific debuggers won't work now. This branch is only to demonstrate that it could be working to have the gtk text editor on windows. I have also tried to open a single .cs file and it worked.

To try run winbuild-debug.bat to compile gnome on windows

**Comment by MakiWolf** [comment]
Replaced by PR 155

**Pull request closed without merging**
